Repository Systemvetardagen/systemvetardagen.se, pull requests merged in 2022-11, with the labels that each got.

#1 fix: the dismatch of path in index.vue
  pages/index.vue
Labels: bug

#10 Create Catalog “map-content-list-list-map-logo-img-uploads-bild3_huvudvy_efter-png-name-test-title-test1”
  assests/img/uploads/bild3_huvudvy_efter.png
  content/Catalog/map-content-list-list-map-logo-img-uploads-bild3_huvudvy_efter-png-name-test-title-test1.md
Labels: netlify-cms/draft

#14 Create Catalog “map-content-list-list-map-logo-img-uploads-use-case-diagram-tier-shop-png-name-test2-title-test2-map-name-page2-title-page2-logo-img-uploads-idef0-model-framtidsläge-page-3-3-png”
  assets/img/uploads/idef0-model-framtidsläge-page-3-3-.png
  assets/img/uploads/use-case-diagram-tier-shop.png
  content/Catalog/map-content-list-list-map-logo-img-uploads-use-case-diagram-tier-shop-png-name-test2-title-test2-map-name-page2-title-page2-logo-img-uploads-idef0-model-framtidsläge-page-3-3-png.md
Labels: netlify-cms/pending_publish

#15 Create Front_Page “test1”
  content/Front_page/test1.md
Labels: netlify-cms/pending_publish

#16 Create Company_page “test1”
  assets/img/uploads/use-case-diagram-tier-shop.png
  content/Company_pages/test1.md
Labels: netlify-cms/pending_publish
