Repository Systemvetardagen/systemvetardagen.se, pull requests merged in 2023-01, with the labels that each got.

#26 Create Company_page “disk”
  assets/img/uploads/symbol_-_text_logo_black_-_color.png
  content/Company_pages/disk.md
Labels: netlify-cms/pending_publish

#27 Create Company_page “test1”
  content/Company_pages/test1.md
Labels: netlify-cms/pending_publish

#28 Create company “test2”
  content/company/test2.md
Labels: netlify-cms/pending_publish

#29 Create company “tgyufk”
  content/company/tgyufk.md
Labels: netlify-cms/pending_publish

#30 Create company “adfs”
  content/company/adfs.md
Labels: netlify-cms/pending_publish

#34 Create company “avanade”
  content/company/avanade.md
Labels: netlify-cms/pending_publish

#39 Update company “avanade”
  content/company/avanade.en.md
  content/company/avanade.sv.md
Labels: netlify-cms/pending_publish

#47 Create company “test”
  content/company/test.en.md
  content/company/test.sv.md
Labels: netlify-cms/pending_publish

#48 Create company “test-1”
  content/company/test-1.en.md
  content/company/test-1.sv.md
Labels: netlify-cms/pending_publish

#59 Landing_contact
  assets/css/main.css
  assets/img/blob-6d-nodImage-white.png
  assets/img/contact-blob-nod.png
  assets/img/soon-provisional.png
  locales/en.json
  locales/sv.json
  package-lock.json
  pages/index-subviews/contact.vue
Labels: Landing page

#68 Create About “group-leader-1”
  content/aboutUs/group-leader-1.en.md
  content/aboutUs/group-leader-1.sv.md
Labels: netlify-cms/pending_publish

#67 Create About “group-leader”
  content/aboutUs/group-leader.en.md
  content/aboutUs/group-leader.sv.md
Labels: netlify-cms/pending_publish

#70 Create About “alex-littorin”
  assets/img/uploads/alex.webp
  assets/img/uploads/björn.webp
  assets/img/uploads/elsa.webp
  assets/img/uploads/giancarlo.webp
  assets/img/uploads/joakim.webp
  assets/img/uploads/josefin.webp
  assets/img/uploads/tommy.webp
  assets/img/uploads/william.webp
  content/about/alex-littorin.en.md
  content/about/alex-littorin.sv.md
Labels: netlify-cms/draft

#71 Create About “josefin-lundgren”
  content/about/josefin-lundgren.en.md
  content/about/josefin-lundgren.sv.md
Labels: netlify-cms/draft

#72 Create About “björn-albin-forsberg”
  content/about/björn-albin-forsberg.en.md
  content/about/björn-albin-forsberg.sv.md
Labels: netlify-cms/draft

#73 Create About “william-nehro”
  content/about/william-nehro.en.md
  content/about/william-nehro.sv.md
Labels: netlify-cms/draft

#74 Create About “elsa-wahlstein”
  content/about/elsa-wahlstein.en.md
  content/about/elsa-wahlstein.sv.md
Labels: netlify-cms/draft

#75 Create About “giancarlo-valverde”
  content/about/giancarlo-valverde.en.md
  content/about/giancarlo-valverde.sv.md
Labels: netlify-cms/draft

#76 Create About “tommy-södergren”
  content/about/tommy-södergren.en.md
  content/about/tommy-södergren.sv.md
Labels: netlify-cms/draft

#77 Create About “joakim-wirén”
  content/about/joakim-wirén.en.md
  content/about/joakim-wirén.sv.md
Labels: netlify-cms/draft

#63 Landing page sponsors section
  assets/img/company-logos/logo_accenture.png
  assets/img/company-logos/logo_capgemini.png
  assets/img/company-logos/logo_cygni.png
  assets/img/company-logos/logo_handelsbanken.png
  assets/img/company-logos/logo_innofactor.png
  assets/img/company-logos/logo_sweco_black.png
  assets/img/company-logos/logo_zimply.png
  nuxt.config.js
  pages/index-subviews/sponsors.vue
Labels: Landing page
